### ISSUE TITLE
Request: get list of users

### ISSUE THREAD

**Issue by T3charmy** [DeepBot-API/client-websocket#1]
Working on a project for someone, and was wondering if there was a way to get a list of users(not necessarily all users at once), something like being able to request 5 users from the top points list starting at position 20. similar to how you can do https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-channelschannelvideos

example: api|get_user_list|:method|:limit|:offset
method default is top, limit default is 10; and a max # of what ever you think is reasonable, offset default is 0

example returned data:
```
{
    "function": "get_user_list",
    "param": {
        "method": "top_points"
        "limit": 10,
        "offset": 20
    },
    "msg": {
        "user21": 4000,
        "user22": 3800,
        "user23": 3750,
        "user24": 3600,
        "user25": 3500,
        "user26": 3450,
        "user27": 3437,
        "user28": 3400,
        "user29": 3200,
        "user30": 2982,
    }
}
```
or possibly

```
    "msg": {
        "user21": {
            "points": 4000,
            "watch_time": 100.2,
            "vip": 10,
            "mod" 5,
            "join_date": "2014-07-05T18:09:10.3156084Z",
            "last_seen": "2015-03-01T04:17:09.545139Z",
            "vip_expiry": "2014-12-09T00:00:00+08:00"
        },
        "user22": {
            ...
        },
        "user23": {
            ...
        },
        "user24": {
            ...
        },
        "user25": {
            ...
        },
        "user26": {
            ...
        },
        "user27": {
            ...
        },
        "user28": {
            ...
        },
        "user29": {
            ...
        },
        "user30": {
            ...
        },
    }
```
or have it as an array of objects and output it like you do get_user

Not sure what data should get returned if it should just be an array of users, or if it should be an array/object of user info. *(maybe have that as an additional param?)*

Would be nice to have more then just getting the top users, may be alphabetical, most hours or something like that.

**Comment by expertsonline** [comment]
Thanks for the feedback - Updated 'get_users' command with the latest update that should hopefully help.
