### ISSUE TITLE
Typo(?) in example response for get_users

### ISSUE THREAD

**Issue by ekimekim** [DeepBot-API/client-websocket#4]
The example response for `get_users` looks like this:
```json
"msg": {
    {
        ...
    },
    {
        ...
    },
    ...
}
```
However, this isn't valid json - the value of `msg` is an object, but you aren't listing any keys.

I'm assuming the intent was for the value of `msg` to be an array (I can't confirm this at the moment as I do not currently have access to a copy of deepbot to test against). ie. that it would look like this:
```json
"msg": [
    {
        ...
    },
    {
        ...
    },
    ...
]
```

**Comment by expertsonline** [comment]
Yes it is a typo. Output is a proper json with square brackets.
Will update it with all the new changes in the next version.
