### ISSUE TITLE
Questions about escrow

### ISSUE THREAD

**Issue by ekimekim** [DeepBot-API/client-websocket#6]
Hi,

Is a user's escrow amount shared state between all connections? Does it get automatically cancelled if the requesting connection disconnects?

What I'm mainly concerned about is that if my process were to suddenly crash, it may accidentally leave a user's points in escrow. This would deprive the user of points permanently until their escrow is interacted with again. At this time, the program attempting to manipulate their escrow may accidentally commit the previously-added points. With this in mind, would it be best practice to call `cancel_escrow` on every user upon startup?

**Comment by expertsonline** [comment]
Escrow are logged in the bot database and shared across all connections. However, these are not committed to the database. So if the bot crashes, the escrow is lost.

Its intended purpose was to prevent crashes from losing points that were not fully used. i.e. raffle entries that have not been drawn.
